version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    container_name: boanbot
    image: boanbot
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn boanbot.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
