version: '3'
services:
  redis:
    image: redis:5.0.3-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass boanbot --port 6379
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    container_name: boanbot
    image: boanbot
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn boanbot.wsgi:application --bind 0.0.0.0:8080
    ports:
      - '8080:8080'
