version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis01
    ports:
            - '6379:6379'
    command: redis-server
    healthcheck:
        test: "redis-cli -h 0.0.0.0 ping"
        interval: 3s
        timeout: 1s
        retries: 5
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    container_name: boanbot
    image: boanbot
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn boanbot.wsgi:application --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - redis:redis
    command: celery -A boanbot worker -l INFO
  celery-beat:
    container_name: celerybeat
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    links:
      - redis:redis
    command: celery -A boanbot beat -l INFO

