# Generated by Django 3.1.5 on 2021-01-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
